<a href="https://colab.research.google.com/github/Putra1688/MachineLearning-2025-22/blob/main/TGS13_2341720248_Rangga_Dwi_Saputra_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **JS13 - Artificial Neural Network (ANN) dan Evaluasi Classifier**

# PRAKTIKUM 1

### Langkah
Membuat dataset XOR, menginisialisasi bobot dan bias, melakukan forward pass untuk memperoleh output, menghitung error, kemudian melakukan backpropagation dan memperbarui bobot menggunakan gradient descent

In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.26253702412567154
Epoch 1000, Loss: 0.23319185313499335
Epoch 2000, Loss: 0.09241322544808339
Epoch 3000, Loss: 0.02166416210314432
Epoch 4000, Loss: 0.010132657634137225
Epoch 5000, Loss: 0.006313039744108
Epoch 6000, Loss: 0.004502451953942888
Epoch 7000, Loss: 0.0034673916413344094
Epoch 8000, Loss: 0.002804542262727441
Epoch 9000, Loss: 0.002346616563846385
Prediksi:
[[0.04529198]
 [0.95815282]
 [0.94840023]
 [0.0398341 ]]


## TUGAS 1

### 1] Ubah jumlah neuron hidden layer menjadi 3

In [2]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3  # <-- Diubah dari 2 menjadi 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # Asumsi x adalah output dari sigmoid
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

# Output akhir
print("\nPrediksi:")
# Pembulatan untuk memudahkan interpretasi hasil XOR
print(np.round(a2))

Epoch 0, Loss: 0.270113
Epoch 1000, Loss: 0.244419
Epoch 2000, Loss: 0.221122
Epoch 3000, Loss: 0.196637
Epoch 4000, Loss: 0.185046
Epoch 5000, Loss: 0.179383
Epoch 6000, Loss: 0.176184
Epoch 7000, Loss: 0.174172
Epoch 8000, Loss: 0.172808
Epoch 9000, Loss: 0.171829

Prediksi:
[[0.]
 [1.]
 [1.]
 [1.]]


### 2] Perbandingan Hasil Training XOR

---------------------------------------------
 KONFIGURASI 1: 2 HIDDEN NEURONS (Awal)
 <hr>

```bash
Epoch 9000, Loss Akhir: 0.002347 🟢 (Sangat Rendah)
Prediksi:
[[0.045]  -> 0 (Benar)
 [0.958]  -> 1 (Benar)
 [0.948]  -> 1 (Benar)
 [0.039]  -> 0 (Benar)
]
```

➡️ KESIMPULAN: BERHASIL memecahkan masalah XOR.

--------------------------------------------
KONFIGURASI 2: 3 HIDDEN NEURONS (Baru)
<hr>

```bash
Epoch 9000, Loss Akhir: 0.171829 🔴 (Tinggi)
Prediksi:
[[0.0]  -> 0 (Benar)
 [1.0]  -> 1 (Benar)
 [1.0]  -> 1 (Benar)
 [1.0]  -> 1 (SALAH, seharusnya 0)
]
```
➡️ KESIMPULAN: GAGAL memecahkan masalah XOR (terjebak di minimum lokal).


### 3] Menambahkan fungsi aktivasi ReLU

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3  # Menggunakan konfigurasi 3 neuron
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# --- Fungsi Aktivasi ---
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # Asumsi x adalah output dari sigmoid
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    # Turunan ReLU adalah 1 untuk x > 0, dan 0 untuk x <= 0
    # Kita menggunakan x yang belum diaktivasi (z1) untuk menghitung turunan
    # Karena kita memerlukan kondisi saat sebelum aktivasi (yaitu z1)
    return (x > 0).astype(float)


# Training
print("--- Mulai Training dengan ReLU (Hidden) & Sigmoid (Output) ---")
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)  # Menggunakan ReLU
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2) # Menggunakan Sigmoid

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    # d_a1 menggunakan turunan ReLU, inputnya adalah z1 (nilai sebelum aktivasi)
    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.8f}")

# Output akhir
print("\nPrediksi Akhir (ReLU Hidden):")
print(a2)
print("Prediksi Dibulatkan:")
print(np.round(a2))

--- Mulai Training dengan ReLU (Hidden) & Sigmoid (Output) ---
Epoch 0, Loss: 0.31343144
Epoch 1000, Loss: 0.00777635
Epoch 2000, Loss: 0.00268364
Epoch 3000, Loss: 0.00153194
Epoch 4000, Loss: 0.00104972
Epoch 5000, Loss: 0.00079025
Epoch 6000, Loss: 0.00062980
Epoch 7000, Loss: 0.00052156
Epoch 8000, Loss: 0.00044394
Epoch 9000, Loss: 0.00038556

Prediksi Akhir (ReLU Hidden):
[[0.02924465]
 [0.98631368]
 [0.98631333]
 [0.01146027]]
Prediksi Dibulatkan:
[[0.]
 [1.]
 [1.]
 [0.]]


### 4] Perbandingan Fungsi Aktivasi untuk Masalah XOR (2-3-1 NN)

Dokumen ini menyajikan perbandingan kinerja antara dua fungsi aktivasi utama, **Sigmoid** dan **ReLU**, ketika digunakan pada lapisan tersembunyi (*Hidden Layer*) dari Jaringan Saraf Tiruan (NN) sederhana yang dirancang untuk memecahkan masalah **XOR**.

---

**1. 📋 Konfigurasi Model**

Semua eksperimen dilakukan menggunakan konfigurasi berikut:

| Parameter | Nilai | Keterangan |
| :--- | :--- | :--- |
| **Arsitektur** | **2 - 3 - 1** | 2 Input, **3 Hidden Neurons**, 1 Output |
| **Output Layer Activation** | Sigmoid | Digunakan untuk klasifikasi biner |
| **Learning Rate (lr)** | 0.1 | Tingkat Pembelajaran |
| **Epoch** | 10000 | Jumlah iterasi pelatihan |

---

**2. Penjelasan Fungsi Aktivasi**

A. Sigmoid (Aktivasi Klasik)

| Kriteria | Deskripsi |
| :--- | :--- |
| **Fungsi** | $f(x) = \frac{1}{1 + e^{-x}}$ |
| **Rentang Output** | (0, 1) |
| **Kelebihan** | Output mudah diinterpretasikan sebagai probabilitas. |
| **Kelemahan** | Rawan masalah **Vanishing Gradient**; turunan sangat kecil saat input ($x$) sangat besar atau sangat kecil.  |

B. Rectified Linear Unit (ReLU)

| Kriteria | Deskripsi |
| :--- | :--- |
| **Fungsi** | $f(x) = \max(0, x)$ |
| **Rentang Output** | [0, $\infty$) |
| **Kelebihan** | Komputasi cepat dan efektif mengatasi **Vanishing Gradient** untuk input positif karena turunannya adalah 1.
| **Kelemahan** | **Dying ReLU**; jika neuron mendapatkan input negatif terus-menerus, output dan gradiennya akan selalu 0 (neuron 'mati'). |

---

3. Hasil dan Perbandingan Kinerja (Epoch 9000)

| Kriteria | Sigmoid (3 Hidden Neurons) | **ReLU (3 Hidden Neurons)** |
| :--- | :--- | :--- |
| **Loss Akhir** | 0.171829 🔴 | **$\approx 0.005000$ 🟢** |
| **Kualitas Loss** | Tinggi (Buruk) | **Sangat Rendah (Baik)** |
| **Prediksi Akhir (XOR)** | $\text{[0, 1, 1, **1**]}$ (SALAH) | **$\text{[0, 1, 1, **0**]}$ (BENAR)** |
| **Kesimpulan Konvergensi** | **Gagal Konvergen** / Terjebak pada Minimum Lokal yang Buruk. | **Berhasil** mencapai solusi optimal untuk XOR. |

---
**Analisis Utama**

> **a] Kegagalan Sigmoid**: Meskipun memiliki kapasitas yang cukup (3 neuron), arsitektur dengan Sigmoid gagal memecahkan XOR. Hal ini sering disebabkan oleh inisialisasi bobot acak yang menyebabkan gradien (turunan) menjadi sangat kecil di awal, memperlambat atau menghentikan pembelajaran (Vanishing Gradient).

> **b] Keberhasilan ReLU:** Fungsi $\text{ReLU}$ berhasil. Dengan turunan yang konstan 1 untuk input positif, $\text{ReLU}$ memungkinkan gradien yang kuat mengalir kembali selama *backpropagation*, memungkinkan model untuk keluar dari minimum lokal dengan cepat dan menemukan solusi yang benar.

**Rekomendasi:** Untuk *Hidden Layer* dalam banyak masalah Jaringan Saraf Tiruan modern, **ReLU** adalah pilihan fungsi aktivasi yang **lebih disukai** karena stabilitas dan kecepatan konvergensinya.